export const bookTranslationMap: Record<string, string> = {
  "Genesis": "उत्पत्ति",
  "Exodus": "निर्गमन",
  "Leviticus": "लैव्यव्यवस्था",
  "Numbers": "गिनती",
  "Deuteronomy": "व्यवस्थाविवरण",
  "Joshua": "यहोशू",
  "Judges": "न्यायियों",
  "Ruth": "रूत",
  "1 Samuel": "1 शमूएल",
  "2 Samuel": "2 शमूएल",
  "1 Kings": "1 राजा",
  "2 Kings": "2 राजा",
  "1 Chronicles": "1 इतिहास",
  "2 Chronicles": "2 इतिहास",
  "Ezra": "एज्रा",
  "Nehemiah": "नहेम्याह",
  "Esther": "एस्तेर",
  "Job": "अय्यूब",
  "Psalms": "भजन संहिता",
  "Proverbs": "नीतिवचन",
  "Ecclesiastes": "सभोपदेशक",
  "Song of Solomon": "श्रेष्ठगीत",
  "Isaiah": "यशायाह",
  "Jeremiah": "यिर्मयाह",
  "Lamentations": "विलापगीत",
  "Ezekiel": "यहेजकेल",
  "Daniel": "दानिय्येल",
  "Hosea": "होशे",
  "Joel": "योएल",
  "Amos": "आमोस",
  "Obadiah": "ओबद्याह",
  "Jonah": "योना",
  "Micah": "मीका",
  "Nahum": "नहूम",
  "Habakkuk": "हबक्कूक",
  "Zephaniah": "सपन्याह",
  "Haggai": "हागै",
  "Zechariah": "जकर्याह",
  "Malachi": "मलाकी",
  "Matthew": "मत्ती",
  "Mark": "मरकुस",
  "Luke": "लूका",
  "John": "यूहन्ना",
  "Acts": "प्रेरितों के काम",
  "Romans": "रोमियों",
  "1 Corinthians": "1 कुरिन्थियों",
  "2 Corinthians": "2 कुरिन्थियों",
  "Galatians": "गलातियों",
  "Ephesians": "इफिसियों",
  "Philippians": "फिलिप्पियों",
  "Colossians": "कुलुस्सियों",
  "1 Thessalonians": "1 थिस्सलुनीकियों",
  "2 Thessalonians": "2 थिस्सलुनीकियों",
  "1 Timothy": "1 तीमुथियुस",
  "2 Timothy": "2 तीमुथियुस",
  "Titus": "तीतुस",
  "Philemon": "फिलेमोन",
  "Hebrews": "इब्रानियों",
  "James": "याकूब",
  "1 Peter": "1 पतरस",
  "2 Peter": "2 पतरस",
  "1 John": "1 यूहन्ना",
  "2 John": "2 यूहन्ना",
  "3 John": "3 यूहन्ना",
  "Jude": "यहूदा",
  "Revelation": "प्रकाशितवाक्य"
};
